from pydantic import BaseModel, Field


class ChatQuery(BaseModel):
    """Schema for the user's query to the assistant."""

    question: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="The question for the AI assistant.",
        examples=["What were the top 3 best-selling products last week?"],
    )


class ChatResponseData(BaseModel):
    """Schema for the data part of the AI assistant's response."""

    answer: str = Field(
        ...,
        description="The answer generated by the AI assistant.",
        examples=[
            "The top 3 best-selling products were 'Product A', 'Product B', and 'Product C'."
        ],
    )
